Document: metalink-checker
Title: Debian metalink-checker Manual
Author: <insert document author here>
Abstract: This manual describes what metalink-checker is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/metalink-checker/metalink-checker.sgml.gz

Format: postscript
Files: /usr/share/doc/metalink-checker/metalink-checker.ps.gz

Format: text
Files: /usr/share/doc/metalink-checker/metalink-checker.text.gz

Format: HTML
Index: /usr/share/doc/metalink-checker/html/index.html
Files: /usr/share/doc/metalink-checker/html/*.html

  
