/*
	This file is part of the metalink program
	Copyright (C) 2005  A. Bram Neijt <bneijt@gmail.com>

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/

#include "Metalink.ih"

void Metalink::insertHeader(std::ostream &str, std::string const &indent)
{
	str << indent << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
	str << indent << "<!-- Metalinks record generated by "
					<< Globals::programName << " " << Globals::version[0] << "." << Globals::version[1] << "." << Globals::version[2];
	str << ", for more information see http://metalinks.sourceforge.net -->\n";
	if(Globals::showDTD)
		str << indent << "<!DOCTYPE metalinks\n"
		      << "\tSYSTEM \"http://metalinks.sourceforge.net/1/metalinks.dtd\"\n"
					<< "\t>\n";


	//XSLT link when xslt is given
	if(!Globals::xsl.empty())
		str << indent
			<< "<?xml-stylesheet type=\"text/xsl\" href=\""
			<< Globals::xsl
			<< "\"?>\n";
			
	str << "\n";
	str << indent << "<metalinks xmlns=\"http://metalinks.sourceforge.net\"\n"
			<< indent << "xmlns:dc=\"http://purl.org/dc/elements/1.1/\">\n";
}
